image: golang:1.15

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - build
  - test

before_script:
  - source support/build.sh
  - install_kubebuilder

tests:
  stage: test
  script:
    - install_kubebuilder
    - make test

build:
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
  services:
    - docker:dind
  stage: build
  script:
    - install_kubebuilder
    - install_docker
    - make docker-build
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - make docker-push
