site_name: Registry Controller
repo_name: "astrokube/registry-controller"
repo_url: https://github.com/astrokube/registry-controller
site_url: https://astrokube.github.io/registry-controller

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      # insert a blank space before the character
      permalink: " ¶"
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Welcome:
    - Welcome: index.md
    - Compatibility: compatibility.md
  - Deployment:
    - Kubernetes: deployment/kubernetes.md
    - OpenShift: deployment/openshift.md
  - 'User guide':
    - 'Integrate AWS ECR': user-guide/aws-ecr.md
    - 'Integrate Docker.io': user-guide/docker-io.md
    - 'AWS ECR Policy': user-guide/aws-ecr-policy.md
  - 'Custom Resource Definitions':
    - ECRCredentials: crd/ecr-credentials.md
  - Examples:
    - ECRCredentials: examples/ecr-credentials.md
  - 'Developer guide':
    - 'Getting started': development/getting-started.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections

  palette:
    primary: "teal"
    accent: "green"

  include_sidebar: true

plugins:
  - search
  - minify:
      minify_html: true
