# permissions for end users to view dockeriocredentials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dockeriocredentials-viewer-role
rules:
- apiGroups:
  - registry.astrokube.com
  resources:
  - dockeriocredentials
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - registry.astrokube.com
  resources:
  - dockeriocredentials/status
  verbs:
  - get
