# permissions for end users to edit dockeriocredentials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dockeriocredentials-editor-role
rules:
- apiGroups:
  - registry.astrokube.com
  resources:
  - dockeriocredentials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - registry.astrokube.com
  resources:
  - dockeriocredentials/status
  verbs:
  - get
