# permissions for end users to view ecrcredentials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ecrcredentials-viewer-role
rules:
- apiGroups:
  - registry.astrokube.com
  resources:
  - ecrcredentials
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - registry.astrokube.com
  resources:
  - ecrcredentials/status
  verbs:
  - get
