# permissions for end users to edit ecrcredentials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ecrcredentials-editor-role
rules:
- apiGroups:
  - registry.astrokube.com
  resources:
  - ecrcredentials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - registry.astrokube.com
  resources:
  - ecrcredentials/status
  verbs:
  - get
