# permissions for end users to edit registrycredentials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: registrycredentials-editor-role
rules:
- apiGroups:
  - registry.astrokube.com
  resources:
  - registrycredentials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - registry.astrokube.com
  resources:
  - registrycredentials/status
  verbs:
  - get
