# permissions for end users to view registrycredentials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: registrycredentials-viewer-role
rules:
- apiGroups:
  - registry.astrokube.com
  resources:
  - registrycredentials
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - registry.astrokube.com
  resources:
  - registrycredentials/status
  verbs:
  - get
