apiVersion: registry.astrokube.com/v1alpha1
kind: RegistryCredentials
metadata:
  name: registrycredentials-sample
spec:
  provider:
    awsElasticContainerRegistrys:
      accessKeyId: 
      secretAccessKey: 
      region: eu-central-1
