name: build-and-push

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl -s https://raw.githubusercontent.com/kubernetes-sigs/kubebuilder/master/scripts/install.sh | sh
      - run: make docker-build

