name: build-and-push

on:
  push:
    branches:
      - master
    paths:
      - '!mkdocs.yml'
      - '!docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl https://raw.githubusercontent.com/kubernetes-sigs/kubebuilder/master/scripts/install.sh | sh
      - run: kubebuilder

